<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生证书管理",
                        "menuJump":"列表",
                        "tableName":"zhengshu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"上课情况管理",
                        "menuJump":"列表",
                        "tableName":"situation"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老师管理",
                        "menuJump":"列表",
                        "tableName":"laoshi"
                    }
                ],
                "menu":"老师管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"班级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBanji"
                    }
                ],
                "menu":"班级管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍信息管理",
                        "menuJump":"列表",
                        "tableName":"sushe"
                    }
					,
					{
                        "buttons":[
                            "删除"
                        ],
                        "menu":"人员与宿舍关系管理",
                        "menuJump":"列表",
                        "tableName":"susheYonghu"
                    }
                ],
                "menu":"宿舍信息管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"证书类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhengshu"
                    }
                ],
                "menu":"基础数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生证书管理",
                        "menuJump":"列表",
                        "tableName":"zhengshu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"上课情况管理",
                        "menuJump":"列表",
                        "tableName":"situation"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改"
                        ],
                        "menu":"宿舍信息管理",
                        "menuJump":"列表",
                        "tableName":"sushe"
                    }
					,
					{
                        "buttons":[
                            "删除"
                        ],
                        "menu":"人员与宿舍关系管理",
                        "menuJump":"列表",
                        "tableName":"susheYonghu"
                    }
                ],
                "menu":"宿舍信息管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"老师",
        "tableName":"laoshi"
    }
	,{
        "backMenu":[
			{
                "child":[
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生证书管理",
                        "menuJump":"列表",
                        "tableName":"zhengshu"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"上课情况管理",
                        "menuJump":"列表",
                        "tableName":"situation"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"宿舍信息管理",
                        "menuJump":"列表",
                        "tableName":"sushe"
                    }
                ],
                "menu":"宿舍信息管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
